
##  _config.yml

# sass properties

sass:

  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

  style: compressed

  logo: "/assets/images/logo.png"
  avatar: "/assets/images/avatar.jpg"
  

# Theme settings

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "default" 

# Site settings
locale: "en-US"
title: "AI, LLM & LLM-HypatiaX Blog"
title_separator: "|"
subtitle: "Exploring generative AI in formula discovery"
name: "Dr. Ruperto Pedro Bonet Chaple"
description: "A blog dedicated to AI, LLM research, and the LLM-HypatiaX project focusing on generative AI in formula discovery."
url: "https://127.0.0.1:4000"
baseurl: ""
repository: "sednabcn/ai-llm-blog"
logo: "/assets/images/logo.png"
masthead_title: "SiMLeng"

# Site Author
author:
  name: "Dr. Ruperto Pedro Bonet Chaple"
  avatar: "/assets/images/avatar.jpg"
  bio: "PhD in Computational Mechanics"
  location: "London,UK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:simleng@modelphysmat.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sednabcn"



# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sednabcn"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruperto-p-bonet-chaple-8a26651b/"
    - label: "Twitter"
      icon: "fab fa-fw fa-X"
      url: "https://twitter.com/BONETCHAPLE"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/RUPERTOPEDROBONET"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@simleng"

# Reading Files
include:
  - _pages

# Outputting
collections:
  _posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
 # Comments
comments:
  provider: "custom"  # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  custom:
    enabled: true
markdown: kramdown  # Make sure this is set
  
# Exclude files from processing

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

