# _config.remote.yml

# Site Configuration for Production Environment
environment: production

head:
  - "<link rel='stylesheet' href='https://sednabcn.github.io/ai-llm-blog/assets/css/utterances-theme.css'>"


# Sass Compilation Settings
sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css
  style: compressed

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "AI, LLM & LLM-HypatiaX Blog"
title_separator: "|"
subtitle: "Exploring generative AI in formula discovery"
name: "Dr. Ruperto Pedro Bonet Chaple"
description: "A blog dedicated to AI, LLM research, and the LLM-HypatiaX project focusing on generative AI in formula discovery."

excerpt_length: 156

# Production URL Configuration

url: "https://sednabcn.github.io"
baseurl: "/ai-llm-blog"

# Repository-Specific Settings
repository: sednabcn/ai-llm-blog
github:
  repository_name: "ai-llm-blog"
  is_project_page: true

# Branding Assets
logo: "/assets/images/logo.png"
masthead_title: "SiMLeng"
favicon: "favicon-16x16.png"

# Site Author Profile
author:
  name: "Dr. Ruperto Pedro Bonet Chaple"
  avatar: "/assets/images/avatar.jpg"
  bio: "PhD in Computational Mechanics"
  location: "London, UK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@modelphysmat.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sednabcn"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruperto-p-bonet-chaple-8a26651b/"

# Site Footer Configuration
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sednabcn"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruperto-p-bonet-chaple-8a26651b/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/BONETCHAPLE"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/RUPERTOPEDROBONET"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@simleng"


# Set which comment system to use
comments:
  provider:  'utterances'          

utterances:
  repo:                "sednabcn/ai-llm-blog"
  issue-term:          "title"
  label:               "💬comments"
  theme:               "https://sednabcn.github.io/ai-llm-blog/assets/css/utterances-theme.css"
  crossorigin:         "anonymous"

# Reading and Processing Settings
include:
  - _pages
  - google2fe61160aa58a7ea.html

# Pagination Configuration

permalink: /posts/:title/

paginate: 5
paginate_path: "/page:num/"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Syntax Highlighting
highlighter: rouge

jekyll-minifier:
  uglifier_args:
    harmony: true
    
# Content Excerpts
excerpt_separator: "\n\n"

# Production-Specific Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-redirect-from

# Minifier Options
jekyll-minifier:
  uglifier_args:
    harmony: true

# Archive Configurations
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Default Page/Post Settings
defaults:
  # Posts defaults
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # Pages defaults
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false

# Custom headers configuration
webrick:
  headers:
    Content-Security-Policy: "frame-ancestors 'self' https://utteranc.es"

# SEO and Performance Optimizations
# Google Services Configuration
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-FFJMQ3HXMK" # Replace with your Google Analytics 4 ID
    anonymize_ip: true  # Set to true for GDPR compliance if needed

google_site_verification: "0l5TbPYQ76ChPVEmXUclBOY04jLkGAAQAKAEm2a0j60"



# Files to Exclude from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
  - LICENSE
