name: Blog Post Comment
description: Template for blog post comments
title: "[Blog] "
labels: ["blog-comment"]
body:
  - type: markdown
    attributes:
      value: |
        ## Blog Post Comments
        This issue is linked to a blog post via Utterances and displays comments from the post.
        
  - type: input
    id: post-title
    attributes:
      label: Post Title
      description: The title of the blog post
      placeholder: "e.g., Introduction to LLMs"
    validations:
      required: true
      
  - type: input
    id: post-url
    attributes:
      label: Post URL
      description: Link to the blog post
      placeholder: "https://sednabcn.github.io/ai-llm-blog/posts/..."
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        Comments made on this issue will appear on the blog post via Utterances.