name: Check Broken Links

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  # Run on schedule (once a week on Monday)
  schedule:
    - cron: '0 0 * * 1'
  # Run when pushing to main branch (optional)
  push:
    branches: [ main ]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install html-proofer
        run: gem install html-proofer -v 5.0.10 nokogiri

      - name: Build site
        run: |
          # If you're using Jekyll, uncomment the following lines
          # gem install bundler jekyll
          # bundle install
          # bundle exec jekyll build

      - name: Check links with html-proofer
        run: |
          cat > check_links.rb << 'EOF'
#!/usr/bin/env ruby
require 'html-proofer'

options = {
  assume_extension: true,
  check_favicon: true,
  check_html: true,
  check_img_http: true,
  enforce_https: true,
  check_opengraph: true,
  cache: {
    timeframe: {
      internal: '2w'
    }
  },
  typhoeus: {
    followlocation: true,
    connecttimeout: 10,
    timeout: 30,
    ssl_verifypeer: false,
    ssl_verifyhost: 0
  }
}

begin
  puts "Checking links in _site directory..."
  proofer = HTMLProofer.check_directory("./_site", options)
  proofer.run
rescue => e
  puts "Error during link checking: #{e.message}"
  exit 1
end
EOF
          chmod +x check_links.rb
          ruby check_links.rb

      - name: Create report artifact
        if: always()
        run: |
          mkdir -p broken_links_report
          mv tmp/.htmlproofer broken_links_report/ || true
          echo "## Broken Links Check Results" > broken_links_report/summary.md
          echo "Check completed at $(date)" >> broken_links_report/summary.md
          echo "For detailed results, see the report files." >> broken_links_report/summary.md

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: broken-links-report
          path: broken_links_report

      - name: Notify on failure
        if: failure()
        run: |
          echo "Broken links were found in the website. Check the GitHub Actions run for details."
          # Add notification steps here if needed (e.g., send email, Slack message)
