name: New Blog Post Issue

on:
  push:
    branches:
      - master  # Runs when a new post is added
    paths:
      - '_posts/**'  # Only trigger on changes to posts

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find latest post
        id: latest_post
        run: |
          LATEST_FILE=$(ls -t _posts/*.md | head -n 1)
          echo "Selected file: $LATEST_FILE"

          # Extract post metadata
          TITLE=$(grep -m 1 "^title:" "$LATEST_FILE" | sed 's/title: //' | sed 's/"//g')
          DATE=$(basename "$LATEST_FILE" | cut -d'-' -f1-3)  # Extracts YYYY-MM-DD
          PERMALINK=$(grep -m 1 "^permalink:" "$LATEST_FILE" | sed 's/permalink: //' || echo "")
          
          if [ -z "$PERMALINK" ]; then
            # If no permalink, create one from filename
            SLUG=$(basename "$LATEST_FILE" | cut -d'-' -f4- | sed 's/\.md$//')
            URL="https://sednabcn.github.io/ai-llm-blog/posts/$SLUG/"
          else
            URL="https://sednabcn.github.io/ai-llm-blog$PERMALINK"
          fi
          
          # Save to GitHub environment variables
          echo "file=$LATEST_FILE" >> $GITHUB_ENV
          echo "title=$TITLE" >> $GITHUB_ENV
          echo "date=$DATE" >> $GITHUB_ENV
          echo "url=$URL" >> $GITHUB_ENV

      - name: Create GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create issue body content
          BODY="## 🚀 New Blog Post Published!
          
          **Title:** ${{ env.title }}
          **Date:** ${{ env.date }}
          
          [Read the full post here](${{ env.url }})
          
          ---
          *This issue is automatically created to track comments for this blog post. Comments made here will appear on the blog post via Utterances.*"
          
          # Create the issue via GitHub API
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d @- << EOF
          {
            "title": "Blog Post: ${{ env.title }}",
            "body": $(echo "$BODY" | jq -Rs .),
            "labels": ["blog-comment"]
          }
          EOF