name: Jekyll Site Deployment

# Triggers
on:
  push:
    branches: ["master"]
  # Allows manual workflow trigger
  workflow_dispatch:

# Permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Ensure only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build and Deploy Job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Setup Ruby with a simpler configuration
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          # Removed bundler-cache to troubleshoot issues

      # Dependency Management
      - name: Install Dependencies
        run: |
          # Check if Gemfile.remote exists and use it
          if [ -f "Gemfile.remote" ]; then
            cp Gemfile.remote Gemfile
          fi
          
          gem install bundler
          bundle install --jobs 4 --retry 3

      # Build Jekyll Site with Environment Configuration
      - name: Build Jekyll Site
        run: |
          # Check if config.remote exists and use it
          if [ -f "_config.remote.yml" ]; then
            cp _config.remote.yml _config.yml
          fi
          
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Deploy to GitHub Pages - using JamesIves action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Performance and Accessibility Check (runs after deployment)
  lighthouse-check:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://sednabcn.github.io/ai-llm-blog
          uploadArtifacts: true