name: Jekyll Site Deployment

# Triggers when code is pushed to master branch or manually triggered
on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Set required permissions
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one deployment at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Primary job to build and deploy the Jekyll site
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

      - name: Install Dependencies
        run: |
          # Use Gemfile.remote if it exists
          if [ -f "Gemfile.remote" ]; then
            cp Gemfile.remote Gemfile
          fi
          
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll Site
        run: |
          # Use remote config if it exists
          if [ -f "_config.remote.yml" ]; then
            cp _config.remote.yml _config.yml
          fi
          
          bundle exec jekyll build
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

  # Performance and accessibility testing after deployment
  lighthouse-check:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://sednabcn.github.io/ai-llm-blog
          uploadArtifacts: true
          artifactName: auditResults2026