name: Test Broken Links

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  broken-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'  # Update as required
          bundler-cache: true
      
      - name: Copy Remote Gemfile and Config (if applicable)
        run: |
          if [ -f Gemfile.remote ]; then cp Gemfile.remote Gemfile; fi
          for f in *config.remote.yml; do
            [ -f "$f" ] && cp "$f" "${f/.remote/}";
          done
	  
      - name: Install dependencies
        run: |
          gem install bundler
          gem install mail
          gem install nokogiri
          bundle install
	  
      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Run Broken Links Checker
        run: ruby ./_tests/sitemap_broken_links_checker.rb https://sednabcn.github.io/ai-llm-blog/

      - name: Show broken link results if available
        if: always()
        run: |
          if ls broken_links_*.txt 1> /dev/null 2>&1; then
            echo "Broken link reports:"
            cat broken_links_*.txt
          else
            echo "No broken link report generated."
          fi

      - name: Upload Broken Links Report
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: broken-links-report
          path: broken_links_*.txt

      - name: Slack Notification on Broken Links
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⚠️ Broken links were found during the Jekyll deployment.\nCheck the logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.EMAIL_WEBHOOK_URL }}

      - name: Send Email on Broken Links
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "⚠️ Broken Links Detected - ${{ github.repository }}"
          body: |
            Broken links were detected during the Jekyll site deployment.
            
            Check the logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.SMTP_USERNAME }}
          from: GitHub Actions
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: high
          # For port 465 specifically:
          encryption: ssl