name: URL Case Correction

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check-and-redirect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create URL redirect script
        run: |
          cat > redirect-script.js << 'EOF'
          // Get all links on the page
          const links = document.getElementsByTagName('a');
          
          // Check each link for capitalization issues
          for (let i = 0; i < links.length; i++) {
            const href = links[i].getAttribute('href');
            if (href && href.includes('/Ai-llm-blog/')) {
              links[i].setAttribute('href', href.replace('/Ai-llm-blog/', '/ai-llm-blog/'));
            }
          }
          
          // Check current URL and redirect if needed
          if (window.location.href.includes('/Ai-llm-blog/')) {
            window.location.href = window.location.href.replace('/Ai-llm-blog/', '/ai-llm-blog/');
          }
          EOF
          
      - name: Add redirect script to head of HTML files
        run: |
          find . -name "*.html" -exec sh -c '
            if ! grep -q "redirect-script.js" "$1"; then
              sed -i "s/<head>/<head>\n<script src=\"\/redirect-script.js\"><\/script>/" "$1"
            fi
          ' sh {} \;
          
      - name: Create redirect script file in root directory
        run: |
          cp redirect-script.js ./_site/redirect-script.js || mkdir -p _site && cp redirect-script.js ./_site/
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Add URL capitalization fix via GitHub Actions" || echo "No changes to commit"
          git push



