name: Auto Version Tag

on:
  push:
    branches: [master]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Update version timestamp
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M")
        sed -i "s|<!--VERSION-->|$TIMESTAMP|g" custom-home.html

    - name: Commit updated file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "🔄 Auto-update version to $TIMESTAMP" || echo "No changes to commit"
        git push
